export const PAYSTACK_MODULE_CONFIG_TOKEN = Symbol(
  'PAYSTACK_MODULE_CONFIG_TOKEN',
);

export const PAYSTACK_CLIENT_TOKEN = Symbol('PAYSTACK_CLIENT_TOKEN');

export const PAYSTACK_WEBHOOK_HANDLER = Symbol('PAYSTACK_WEBHOOK_HANDLER');

export const PAYSTACK_WEBHOOK_SERVICE = Symbol('PAYSTACK_WEBHOOK_SERVICE');
